version: '3.7'
services:
  postgres:
    image: postgres
    shm_size: 1g
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
      - 5432:5432/tcp
  api:
    container_name: api
    depends_on:
      - postgres
    build:
      context: .
      target: dev
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://test:password@postgres:5432/test?schema=public"
    ports:
      - 3000:3000/tcp
    volumes:
      - "./src:/app/src"
