version: '3.7'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  api:
    container_name: api
    depends_on:
      - mongodb
    build:
      context: .
      target: dev
    environment:
      PORT: 3000
      DATABASE_URL: "mongodb://root:root@mongodb:27017/test?authSource=admin"
    ports:
      - 3000:3000/tcp
    volumes:
      - "./src:/app/src"

volumes:
  mongodb_data: